name: Build
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y build-essential git python3-dev ffmpeg libsdl2-dev libsdl2-image-dev libsdl2-mixer-dev libsdl2-ttf-dev libportmidi-dev libswscale-dev libavformat-dev libavcodec-dev zlib1g-dev
          pip3 install --user buildozer Cython==0.29.33
      - name: Build with Buildozer
        run: |
          export PATH=$PATH:~/.local/bin
          yes | buildozer -v android debug
      - name: Upload APK
        uses: actions/upload-artifact@v2
        with:
          name: Yemen-Tool-Package
          path: bin/*.apk
