name:Build
on:[push]
jobs:
apk:
runs-on:ubuntu-latest
steps:
-uses:actions/checkout@v2
-name:Setup
run:pipinstallbuildozercython==0.29.33
-name:Build
run:
sudoaptupdate
sudoaptinstall-ybuild-essentialgitpython3-devffmpeglibsdl2-devzlib1g-devyes|buildozer-androiddebug
-name:Upload
uses:actions/upload
-artifact@v2
with:
name:App-Package
path:bin/*.apk
